### ISSUE TITLE
Search returns 404

### ISSUE THREAD

**Issue by xavierraffin** [gethugothemes/liva-hugo#44]
I am running a blog with Liva and the search results page returns 404.

URL: https://visualping.io/blog/
Search result: https://visualping.io/blog/search?s=monitor

My config.toml:

```toml
######################## default configuration ####################
baseURL = "https://visualping.io/blog"
languageCode = "en-us"
title = "Visualping blog"
theme = "liva"
summaryLength = "20"
paginate = 6
disqusShortname = ""
relativeURL = "true"
DefaultContentLanguage = "en"


[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "Home"
  URL = "https://visualping.io"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "/"
  weight = 2
...

#################### default parameters ################################
[params]
logo = "images/logo-blue@2x.png"
logoDark = "images/logo-dark.png"
clock = "images/icon-clock.png"
home = "Home"
# Meta data
...

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true



############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/intent/tweet?url="
...

################################ languages #############################

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    title = "The Visualping Blog"
    weight = 1
    ...

```

Example search results (403 from S3 because the target file do not exist). It returns a 404 when running locally.

https://visualping.io/blog/search?s=monitor

Thank you very much for your help
